name: "01 Provision Infra Minimal WD"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        type: choice
        options: ["dev", "stage", "prod"]
      apply:
        description: "APPLY"
        type: string
        default: "false"
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      apply:
        required: false
        type: string
        default: "false"
    secrets:
      AWS_ROLE_ARN:
        required: false

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Test"

  terraform:
    needs: [test]
    name: "Terraform"
    permissions:
      contents: read
      id-token: write
    uses: thisisblaze/blaze-actions/.github/workflows/reusable-terraform.yml@main
    with:
      environment: ${{ inputs.environment }}
      cloud_provider: "aws"
      tf_dir: "live/dev/network"
      aws_region: "us-east-1"
      bucket: "test-bucket"
      state_key: "test.tfstate"
      lock_table: "test-lock"
      apply: ${{ inputs.apply && 'true' || 'false' }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
