name: "01 Provision Infra Minimal"
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project:
        required: false
        type: string
        default: "thisisblaze"
      stack:
        required: false
        type: string
        default: "network"
      cloud_provider:
        required: false
        type: string
        default: "aws"
      apply:
        required: false
        type: boolean
        default: false
    secrets:
      AWS_ROLE_ARN:
        required: false
      GH_PAT:
        required: false

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Test with workflow_dispatch"
