name: Debug Ops
on:
    workflow_call:
        inputs:
            action:
                type: string
                required: true
            environment:
                type: string
                required: false
            stack:
                type: string
                required: false
            branch_tag:
                type: string
                required: false
            confirmation:
                type: string
                required: false
        secrets:
            AWS_ROLE_ARN:
                required: true
            GH_PAT:
                required: false

jobs:
    debug:
        runs-on: ubuntu-latest
        steps:
            - name: Hello
              run: echo "Hello from Debug Ops"

            - name: Print Inputs
              run: echo "Action input received"
