name: Calculate Configuration

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      cloud_provider:
        required: false
        type: string
        default: ""
      terraform_stack:
        required: false
        type: string
      branch_tag:
        required: false
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: false
    outputs:
      stage_key:
        value: ${{ jobs.calculate.outputs.stage_key }}
      project_key:
        value: ${{ jobs.calculate.outputs.project_key }}
      client_key:
        value: ${{ jobs.calculate.outputs.client_key }}
      namespace:
        value: ${{ jobs.calculate.outputs.namespace }}
      infra_prefix:
        value: ${{ jobs.calculate.outputs.infra_prefix }}

jobs:
  calculate:
    name: Calculate Config
    runs-on: ubuntu-latest
    outputs:
      stage_key: "dev"
      project_key: "thisisblaze"
      client_key: "b9"
      namespace: "blaze"
      infra_prefix: ".github/azure/infra/live"
    steps:
      - run: echo "mock"
