name: Calculate Configuration

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      cloud_provider:
        required: false
        type: string
        default: ""
      terraform_stack:
        required: false
        type: string
      branch_tag:
        required: false
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: false
    outputs:
      stage_key:
        value: ${{ jobs.calculate.outputs.stage_key }}
      project_key:
        value: ${{ jobs.calculate.outputs.project_key }}
      client_key:
        value: ${{ jobs.calculate.outputs.client_key }}
      namespace:
        value: ${{ jobs.calculate.outputs.namespace }}
      infra_prefix:
        value: ${{ jobs.calculate.outputs.infra_prefix }}

jobs:
  calculate:
    name: Calculate Config
    runs-on: ubuntu-latest
    outputs:
      stage_key: ${{ steps.config.outputs.stage_key }}
      project_key: ${{ steps.config.outputs.project_key }}
      client_key: ${{ steps.config.outputs.client_key }}
      namespace: ${{ steps.config.outputs.namespace }}
      infra_prefix: ${{ steps.config.outputs.infra_prefix }}
    steps:
      - uses: actions/checkout@v4
      - name: Calculate Configuration
        id: config
        run: |
          echo "stage_key=dev" >> $GITHUB_OUTPUT
          echo "project_key=thisisblaze" >> $GITHUB_OUTPUT
          echo "client_key=b9" >> $GITHUB_OUTPUT
          echo "namespace=blaze" >> $GITHUB_OUTPUT
          echo "infra_prefix=.github/azure/infra/live" >> $GITHUB_OUTPUT
