name: "Test One Input"
on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      timeout-minutes: 30
      - run: echo "${{ inputs.env_name }}"
