name: "Test With Bool"
on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      apply:
        required: false
        type: boolean
        default: false
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      timeout-minutes: 30
      - run: echo "${{ inputs.env_name }} ${{ inputs.apply }}"
